# Generated by Django 3.1.7 on 2021-06-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymanagement',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
