# Generated by Django 3.1.7 on 2021-06-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_categorymanagement_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmanagement',
            name='final',
            field=models.IntegerField(default=0),
        ),
    ]
