# Generated by Django 3.1.7 on 2021-07-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210630_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmanagement',
            name='final',
            field=models.IntegerField(),
        ),
    ]
