# Generated by Django 3.1.7 on 2021-07-04 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_usermanagement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermanage',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
