# Generated by Django 3.1.7 on 2021-07-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_ordermanage_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='image',
            field=models.ImageField(blank=True, default='userimg.png', null=True, upload_to='images/'),
        ),
    ]
