# Generated by Django 3.1.7 on 2021-07-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20210705_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='image',
            field=models.ImageField(blank=True, default='user/images/userimg.png', null=True, upload_to='images/'),
        ),
    ]
