# Generated by Django 3.1.7 on 2021-07-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210705_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
