# Generated by Django 3.1.7 on 2021-07-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210705_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermanage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productmanagement'),
        ),
    ]
