# Generated by Django 3.1.7 on 2021-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20210707_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmanagement',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
